### ISSUE TITLE
Restart error

### ISSUE THREAD

**Issue by oke24** [peterbaumert/ioBroker.vofo-speedtest#114]
Mit der Version 0.0.10 erhalte ich folgende Fehlermeldung im iobroker log:

```
javascript.0 | 2022-04-29 18:12:04.208 | error | script.js.common.SmartHome.RestartVoFoSpeedtest: ReStartVodafonSpeedtest: ERROR:
-- | -- | -- | --
javascript.0 | 2022-04-29 18:12:04.207 | error | script.js.common.SmartHome.RestartVoFoSpeedtest: Wir gehen davon aus, dass der lokale Systemadministrator Ihnen die Regeln erklärt hat. Normalerweise läuft es auf drei Regeln hinaus: #1) Respektieren Sie die Privatsphäre anderer. #2) Denken Sie nach, bevor Sie tippen. #3) Mit großer Macht kommt große Verantwortung. sudo: Kein TTY vorhanden und kein »askpass«-Programm angegeben

```

Bei älteren Adapter-Versionen hatte ich ebenfalls Meldungen, dass ein Restart aufgrund eines bereits laufenden VoFoSpeedtest Prozesses nicht möglich ist. Die obige Meldung ist neu. 

Der scheduler steht auf 11. und 41. Minute pro Stunde ("11,41 * * * *"), so dass sich 2 Prozesse eigentlich nicht blockieren sollten.

**Comment by peterbaumert** [comment]
Das ist aber ein fehler in einem javascript und nicht in dem Adapter oder?

**Comment by oke24** [comment]
Hallo Peter, vielen Dank für den Hinweis auf das Script, welches ich übersehen habe. 
Ja, das Javascript ist ein Kill-Script für hängenbleibende vofo-speedtest - Prozesse. Und das ist mein eigentliches Problem.

Ich habe das Script deaktiviert, die vofo-speedtest Instanz, den Adapter und den zugehörigen Datenpunktbaum gelöscht,  und danach die aktuelle Adapter-Version 0.0.10 neu installiert um einen sauberen Aufsetzpunkt zu haben.

Es fällt auf das die Instanz 0 im Baum nun nicht mehr aufgebaut wird. 

![vofo-1](https://user-images.githubusercontent.com/46261409/166737003-ec02e992-b823-478b-a673-df284540d5d0.png)

![vofo-2](https://user-images.githubusercontent.com/46261409/166800167-8ce1572c-41b0-41fe-957c-0c9000de1c61.png)

Bei ersten Start von vofo-speedtest erhalte ich dann diese Meldungen

```
vofo-speedtest.0 | 2022-05-04 19:41:08.230 | silly | States system redis pmessage system.adapter.vofo-speedtest.0.logLevel/system.adapter.vofo-speedtest.0.logLevel:{"val":"silly","ack":true,"ts":1651686068208,"q":0,"from":"system.adapter.vofo-speedtest.0","lc":1651686068208}
-- | -- | -- | --
vofo-speedtest.0 | 2022-05-04 19:41:08.116 | info | starting. Version 0.0.10 in /opt/iobroker/node_modules/iobroker.vofo-speedtest, node: v12.22.5, js-controller: 4.0.23
vofo-speedtest.0 | 2022-05-04 19:41:07.811 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
vofo-speedtest.0 | 2022-05-04 19:41:07.803 | debug | Plugin sentry Initialize Plugin (enabled=true)
```
Der Adapter bleibt scheinbar beim starten hängen.

Zur nächsten Ausführungszeit kommt dann diese Meldung ins logfile:

`host.okpi4 | 2022-05-04 20:11:04.142 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 31867`

was wieder auf auf mein altes Problem mit hängenbleibenden Prozessen führt.  Ich bin für jeden Hinweis dankbar !

**Comment by peterbaumert** [comment]
Hey, ja das problem mit dem hängen bleiben versuche ich gerade zu fixen.

Das problem bei dir ist, das auch wenn du den "deinstallierst" der hängende prozess an sich noch da ist.
Den musst du entweder manuell auf der shell abschießen oder einmal den host neustarten.

Gruß
Pete

**Comment by oke24** [comment]
Hi Pete, hmm -  die Vorgehensweise klappt leider noch nicht bei mir. Ich habe jetzt die Instanz gelöscht, dann den zugehörigen Objektbaum, anschließend den Prozess auf der Shell abgeschossen. Dann zur Sicherheit den Host neu gestartet und eine neue vofo 0.0.10 Instanz installiert. Aber der Prozess kommt nicht übers starten hinaus:

```
vofo-speedtest.0 | 2022-05-05 21:27:07.922 | info | starting. Version 0.0.10 in /opt/iobroker/node_modules/iobroker.vofo-speedtest, node: v12.22.5, js-controller: 4.0.23
vofo-speedtest.0 | 2022-05-05 21:27:07.423 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

```
Er bleibt einfach hängen und tut scheinbar nichts. Auch der host hat dazu keine Meldungen im Logfile.
Bei der Erstinstallation von vofo vor vielen Monaten klappte der erste Prozess-Start und Aufbau des Objektbaums, nur dass hier dann die Prozeßhänger nach gewisser Zeit auftraten. Jetzt klappt bereits die erste Ausführung nicht, der Objektbaum ist wie im Bild oben gezeigt leer. Ich bin ratlos.

**Comment by oke24** [comment]
Ich habe nochmals alles gelöscht und den Adapter über die Gitlab-URL neu eingerichtet. Dabei wurde der Objektbaum nun wieder angelegt. 

Ich habe damit jetzt nur noch das Problem des hängenbleibenden Prozesses io.vofo-speedtest.0.

**Comment by oke24** [comment]
.. läuft jetzt 24h bei mir ! bislang ist kein  vofo-Prozeß hängengeblieben ...

**Comment by jk-andersen** [comment]
Läuft bei mir auch seit 2 Tagen sauber durch. Danke!

**Comment by peterbaumert** [comment]
Danke für die Rückmeldungen. Dann mache ich mal eine neue Version draus.

**Comment by peterbaumert** [comment]
should be fixed in https://github.com/peterbaumert/ioBroker.vofo-speedtest/commit/c48812c8d7fec631cc3e46ab57f39a8b8053d60e
