### ISSUE TITLE
Deinstallation klappt nicht

### ISSUE THREAD

**Issue by daniel-lo** [peterbaumert/ioBroker.vofo-speedtest#120]
Hi, ich hab grad die V.11 als update angeboten bekommen obwohl der Adapter gar nicht mehr installiert ist .. zumindest gibt es keine Instanz. In der Adapterliste steht auch danach noch, dass 0.10 installiert und 0.11 im Angebot ist. Hab auch schon versucht eine Instanz zu installieren/deinstallieren .. aber ich krieg das nicht bereinigt. Vermutlich hat die Deinstallation was gemacht, das nun dazu führt, dass der Adapter irgendwo im Nirvana hängt.

Aktuell benötige ich den Adapter nicht .. und möchte ihn nur sauber wieder aus dem System entfernen.

**Comment by peterbaumert** [comment]
Das wäre an sich dann ein thema vom iobroker selbst. Der adapter hat nichts mit der installation/deinstallation zu tun. Haste den ganzen iobroker server mal neugestartet? Evtl hängt da noch eine zombie process von dem adapter rum

**Comment by peterbaumert** [comment]
Nur einmal installieren und dann deinstallieren. Anderenfalls musste mal bei ioBroer direkt nachfragen. Im discord evtl.

**Comment by Apollon77** [comment]
In der Adapter Zeile ist ein Papierkorb icon ... was passiert denn wenn du da druf klickst? an sich sollte das ein "iob del vofo-speedtest" ausführen was den adapter und alle ggf existierenden Instanzen löscht.

Was ist die Ausgabe?

**Comment by daniel-lo** [comment]
Ja bereinigt alles .. nur ist er jetzt auch aus der Adapterliste verschwunden (deshalb hatte ich da vorher nicht drauf geklickt):

Process exited with code 0
weniger
mehr
$ iobroker del vofo-speedtest
Delete adapter "vofo-speedtest"
host.iobroker Counted 1 adapter for vofo-speedtest
host.iobroker Counted 2 channels of vofo-speedtest
host.iobroker Counted 13 states of vofo-speedtest
host.iobroker Counted 13 states (io.vofo-speedtest.*) from states
host.iobroker Counted 11 states (system.adapter.vofo-speedtest.*) from states
host.iobroker file vofo-speedtest.admin deleted
host.iobroker object vofo-speedtest deleted
host.iobroker object vofo-speedtest.admin deleted
host.iobroker Deleting 16 object(s).
host.iobroker Deleting 24 state(s).
removed 41 packages in 17.469s

113 packages are looking for funding run `npm fund` for details

Process exited with code 0

**Comment by Apollon77** [comment]
Ich dachte das wolltest Du? Oder was genau wolltest du? Ich bin verwirrt

**Comment by daniel-lo** [comment]
naja .. wenn der Adapter aus der Adapterliste verschwindet kann ich ihn ja nicht mehr installieren. Bin der Meinung es wäre sonst so .. dass es auch keine Updates mehr gibt, wenn es keine Instanz mehr gibt.

**Comment by Apollon77** [comment]
> Bin der Meinung es wäre sonst so .. dass es auch keine Updates mehr gibt, wenn es keine Instanz mehr gibt.

Das ist falsch.

Wenn einn Adapter isnatlliert wird dann liegen seine JavaScript Dateien dort und man kann Instanzen einrichten. Ein Update bedeutet das die JavaScript Dateien aktualisiert werden. Das wird auch angeboten wenn Du keine Instanz hast.

**Comment by daniel-lo** [comment]
Dann lag ich falsch und muss mich entschuldigen.

**Comment by Apollon77** [comment]
Alles gut :-)
