### ISSUE TITLE
Installationsfehler unter Node 18.15.0

### ISSUE THREAD

**Issue by Knallochse** [peterbaumert/ioBroker.vofo-speedtest#160]
Der Adapter lässt sich unter Node 18.15.0 nicht mehr installieren.

`$ iobroker add vofo-speedtest auto --host buanet-iobroker1 --debug

NPM version: 9.5.0

Installing iobroker.vofo-speedtest@0.0.13... (System call)

npm ERR! code 1

npm ERR! gyp info spawn args '-f',npm ERR! gyp info spawn args 'make',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/node-libcurl/build/config.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/.cache/node-gyp/18.15.0/include/node/common.gypi',npm ERR! gyp info spawn args '-Dlibrary=shared_library',npm ERR! gyp info spawn args '-Dvisibility=default',npm ERR! gyp info spawn args '-Dnode_root_dir=/opt/iobroker/.cache/node-gyp/18.15.0',npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',npm ERR! gyp info spawn args '-Dnode_lib_file=/opt/iobroker/.cache/node-gyp/18.15.0/<(target_arch)/node.lib',npm ERR! gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/node-libcurl',npm ERR! gyp info spawn args '-Dnode_engine=v8',npm ERR! gyp info spawn args '--depth=.',npm ERR! gyp info spawn args '--no-parallel',npm ERR! gyp info spawn args '--generator-output',npm ERR! gyp info spawn args 'build',npm ERR! gyp info spawn args '-Goutput_dir=.'npm ERR! gyp info spawn args ]npm ERR! Could not run curl-config, please make sure libcurl dev package is installed.

npm ERR! A complete log of this run can be found in:npm ERR! /opt/iobroker/.npm/_logs/2023-04-04T09_56_47_982Z-debug-0.log

host.buanet-iobroker1 Cannot install iobroker.vofo-speedtest@0.0.13: 1

ERROR: Process exited with code 25`

**Comment by Grothesk242** [comment]
Kein Issue mit nodejs, da fehlen dev-packages. 

```
sudo apt update
apt policy libcurl4-gnutls-dev libcurl4-nss-dev libcurl4-openssl-dev
```
Oder wie auch immer man das in Docker macht...

**Comment by Knallochse** [comment]
Vielen Dank. Läuft. Sorry und Issues kann zu

**Comment by Grothesk242** [comment]
Eigene Issues kannst du auch selber schließen.
