### ISSUE TITLE
Adapter not working suddenly

### ISSUE THREAD

**Issue by jk-andersen** [peterbaumert/ioBroker.vofo-speedtest#76]
Error on adapter since 3 days now - Restart did not fix it.
iobroker 3.3.20
Node.js 14.18.1

<html>
<body>

odafone-speedtest.0 | 2021-11-26 17:00:02.699 | error | init_sbc: Unknown Error
-- | -- | -- | --
vodafone-speedtest.0 | 2021-11-26 17:00:01.719 | error | init_sbc: Unknown Error
vodafone-speedtest.0 | 2021-11-26 17:00:00.746 | error | init_sbc: Unknown Error
vofo-speedtest.0 | 2021-11-26 16:45:32.822 | error | init_sbc: Unknown Error
vofo-speedtest.0 | 2021-11-26 16:45:32.654 | error | doSpeedtest: init_done=false gotConfig=false

</body>
</html>

**Comment by ARM-Mac** [comment]
Same Problem

**Comment by peterbaumert** [comment]
they changed something at the backend, will try to fix

**Comment by peterbaumert** [comment]
Can u try newest github master?

**Comment by jk-andersen** [comment]
Different result, seems better, but not fixed.
No results in the Objects.

<html>
<body>


host.iobroker | 2021-11-30 19:19:14.423 | error | instance system.adapter.vofo-speedtest.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
vofo-speedtest.0 | 2021-11-30 19:19:14.248 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
vofo-speedtest.0 | 2021-11-30 19:19:14.247 | info | terminating
vofo-speedtest.0 | 2021-11-30 19:19:14.247 | info | cleaned everything up...
vofo-speedtest.0 | 2021-11-30 19:19:14.247 | info | starting cleanup...
vofo-speedtest.0 | 2021-11-30 19:19:14.243 | error | Curl handle is closed.
vofo-speedtest.0 | 2021-11-30 19:19:14.242 | error | Error: Curl handle is closed. at Curl.close (/opt/iobroker/node_modules/node-libcurl/lib/Curl.ts:839:17) at Timeout.stopDownloadTest (/opt/iobroker/node_modules/iobroker.vofo-speedtest/main.js:789:29) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7)
vofo-speedtest.0 | 2021-11-30 19:19:14.242 | error | uncaught exception: Curl handle is closed.
vofo-speedtest.0 | 2021-11-30 19:19:00.515 | info | starting. Version 0.0.8 in /opt/iobroker/node_modules/iobroker.vofo-speedtest, node: v14.18.1, js-controller: 3.3.21


</body>
</html>

**Comment by peterbaumert** [comment]
Thanks for testing. Will check the curl part 👍

**Comment by jk-andersen** [comment]
Leider hängt sich der Prozess jeden Tag mehrfach auf in der neuen Version:

<html>
<body>


host.iobroker | 2021-12-02 14:42:00.009 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 13777
-- | -- | -- | --
host.iobroker | 2021-12-02 14:32:00.010 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 13777
host.iobroker | 2021-12-02 14:22:00.009 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 13777
host.iobroker | 2021-12-02 14:12:00.009 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 13777
host.iobroker | 2021-12-02 14:02:00.010 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 13777
host.iobroker | 2021-12-02 13:52:00.009 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 13777
host.iobroker | 2021-12-02 13:42:00.009 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 13777
host.iobroker | 2021-12-02 13:32:00.009 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 13777


</body>
</html>

**Comment by Grothesk242** [comment]
Alle 10 Minuten das skript zu starten dürfte auch etwas zu häufig sein.

**Comment by jk-andersen** [comment]
> 

Da stimme ich absolut nicht zu

**Comment by peterbaumert** [comment]
> > Alle 10 Minuten das skript zu starten dürfte auch etwas zu häufig sein.
> 
> 
> 
> Da stimme ich absolut nicht zu

Das kann aber zu Problemen führen weil die Vodafone dann blocked. Wenn man zu häufig den Speedtest macht ist es das selbe. Kann sein dass ich den fall nicht abgefangen habe und daher das hängen bleiben passiert.

**Comment by peterbaumert** [comment]
Habe nochmal was angepasst, die API Key erkennung war net ganz ok.

**Comment by jk-andersen** [comment]
Hab upgedated - Melde mich morgen mit erfahrungen. Curl klappt schonmal

**Comment by jk-andersen** [comment]
Bei mir hängt sich der Prozess nach dem ersten Lauf leider auf. Sogar wenn ich nur stündlich laufen lasse.

<html>
<body>


host.iobroker | 2021-12-08 10:02:00.011 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 5403
-- | -- | -- | --
host.iobroker | 2021-12-08 09:02:00.011 | warn | instance system.adapter.vofo-speedtest.0 already running with pid 5403


</body>
</html>

**Comment by nicomania** [comment]
Ich habe die genau gleichen Meldungen im Log wie @jk-andersen. Ich nutze den Adapter mit 1&1 DSL im stündlichen Takt. Nach 2 Tagen keine Ergebnisse mehr und die obigen warnings.

**Comment by rookie50** [comment]
Hi, ich habe gerade Version 0.0.10 installiert und bekomme wie schon vorher die Meldung:
instance system.adapter.vofo-speedtest.1 terminated with code 1 (JS_CONTROLLER_STOPPED)
Ich habe den Adapter schon auf debugging gestellt, leider gibt es dort nicht mehr Meldungen.
Mein System: Synology mit ioBroker v6 Docker, JS-Controller 3.3.22, Node.js 14.18.2
Gruß Rookie50

**Comment by peterbaumert** [comment]
ich schaue es mir die tage nochmal an

**Comment by JohGrei** [comment]
Auch bei mir täglich
`2022-01-22 05:18:00.004 - warn: host.VM-Slave instance system.adapter.vofo-speedtest.0 already running with pid 112774`. 
Hier hilft dann nur mehr ein `sudo kill -9 112774` ein Restart des Adapters löst das Problem nicht.

**Comment by jens-maus** [comment]
Hier genau das selbe verhalten. Der Adapter freezed alle paar Tage nachts komplett ein sodass der `io.vofo-speedtest.0` prozess hängen bleibt und lediglich ein manueller `kill` auf der kommandozeile es wieder erlaubt das anhand der schedule er wieder gestartet wird.

**Comment by JohGrei** [comment]
> Hier genau das selbe verhalten. Der Adapter freezed alle paar Tage nachts komplett ein sodass der `io.vofo-speedtest.0` prozess hängen bleibt und lediglich ein manueller `kill` auf der kommandozeile es wieder erlaubt das anhand der schedule er wieder gestartet wird.

Hab mich derzeit (bis zu einer Lösung) mit einem JS-Script beholfen.

function ReStartVodafonSpeedtest() {
    exec('sudo kill -9 $(pidof io.vofo-speedtest.0)', function(err, stdout, stderr) {
        if (err) {
            log(stderr,'error');
            log('ReStartVodafonSpeedtest: ERROR: ', 'error');
            return;
        }
    });
}

onLog('warn', data => {
let text = data.message;
    if (text.match('adapter.vofo-speedtest.0 already running')) {    
        log('MATCH: vofo-speedtest.0: RESTART:' + data.message, 'warn');
        setTimeout(ReStartVodafonSpeedtest, 60*1000);
    }
});

**Comment by JohGrei** [comment]
Bei mir funktioniert der Adapter seit gestern Nachmittag nicht mehr. Auch aus dem Log ist nicht wirklich was ersichtlich. Ist da was bekannt.


```
2022-03-30 09:48:00.435 - debug: vofo-speedtest.0 (5218) Redis Objects: Use Redis connection: 10.0.0.227:9001
--
2022-03-30 09:48:00.462 - debug: vofo-speedtest.0 (5218) Objects client ready ... initialize now
2022-03-30 09:48:00.464 - debug: vofo-speedtest.0 (5218) Objects create System PubSub Client
2022-03-30 09:48:00.465 - debug: vofo-speedtest.0 (5218) Objects create User PubSub Client
2022-03-30 09:48:00.499 - debug: vofo-speedtest.0 (5218) Objects client initialize lua scripts
2022-03-30 09:48:00.504 - debug: vofo-speedtest.0 (5218) Objects connected to redis: 10.0.0.227:9001
2022-03-30 09:48:00.505 - silly: vofo-speedtest.0 (5218) redis psubscribe cfg.o.system.user.*
2022-03-30 09:48:00.525 - silly: vofo-speedtest.0 (5218) redis psubscribe cfg.o.enum.*
2022-03-30 09:48:00.527 - silly: vofo-speedtest.0 (5218) objectDB connected
2022-03-30 09:48:00.528 - debug: vofo-speedtest.0 (5218) Redis States: Use Redis connection: 10.0.0.227:9000
2022-03-30 09:48:00.543 - debug: vofo-speedtest.0 (5218) States create System PubSub Client
2022-03-30 09:48:00.544 - debug: vofo-speedtest.0 (5218) States create User PubSub Client
2022-03-30 09:48:00.570 - debug: vofo-speedtest.0 (5218) States connected to redis: 10.0.0.227:9000
2022-03-30 09:48:00.571 - silly: vofo-speedtest.0 (5218) statesDB connected
2022-03-30 09:48:00.664 - debug: vofo-speedtest.0 (5218) Plugin sentry Initialize Plugin (enabled=true)
2022-03-30 09:48:00.941 - info: vofo-speedtest.0 (5218) starting. Version 0.0.10 in /opt/iobroker/node_modules/iobroker.vofo-speedtest, node: v14.19.1, js-controller: 4.0.21
2022-03-30 09:48:00.998 - silly: vofo-speedtest.0 (5218) States system redis pmessage system.adapter.vofo-speedtest.0.logLevel/system.adapter.vofo-speedtest.0.logLevel:{"val":"silly","ack":true,"ts":1648626480968,"q":0,"from":"system.adapter.vofo-speedtest.0","lc":1648626480968}
2022-03-30 10:03:00.003 - warn: host.VM-Slave instance system.adapter.vofo-speedtest.0 already running with pid 5218


```

**Comment by peterbaumert** [comment]
habe nun noch an ein paar stellen was angepasst. wer lust hat kann schonmal die master git version testen. neue iobroker version kommt dann sobald es positive erkentnisse gibt

**Comment by peterbaumert** [comment]
should be fixed in https://github.com/peterbaumert/ioBroker.vofo-speedtest/commit/c48812c8d7fec631cc3e46ab57f39a8b8053d60e

**Comment by Mephisto090** [comment]
Reopen

Hej,

pünktlich jeden Tag ab um 3 Uhr passiert das hier :(

`instance system.adapter.vofo-speedtest.0 already running with pid`
