### ISSUE TITLE
Vofo-Speedtest v0.0.9 nicht updatebar

### ISSUE THREAD

**Issue by Troox73** [peterbaumert/ioBroker.vofo-speedtest#82]
**Describe the bug**  

IOBroker bietet mir v0.0.9 an, aber auch eine Neuinstallation des Adapters installiert nur v0.0.8 und es wird weiterhin ein update auf v0.0.9 angeboten ;-)

**Versions:**  
 - Adapter version: v0.0.9
 - JS-Controller version: v12.22.8
 - Node version: v12.22.8 / NPM v6.14.15
 - Operating system: Linux/RaspberryOS

**Comment by daniel-lo** [comment]
Auch bei mir nicht updaebar weder über Info noch über Adapterseite oder Git.

**Comment by peterbaumert** [comment]
japs habe den fehler

**Comment by peterbaumert** [comment]
fixed with v0.0.10
